### ISSUE TITLE
lomax: Better error messages on misconfigured input.

### ISSUE THREAD

**Issue by simar7** [opendns/lemming#43]
Currently upon a misconfigured test bench with an option either missing or ill-defined, the testbench throws the following error:

```
➜  lomax git:(master) ✗ ./lomax --vector=openstack-generic-test-select.json --config=openstack-generic-config.json
panic: interface conversion: interface is nil, not int

goroutine 1 [running]:
runtime.panic(0x6011a0, 0xc21004f5c0)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.initPtrs()
        /home/simar/syseng/gocode/src/github.com/opendns/lemming/lomax/lomax.go:75 +0x2ad
main.main()
        /home/simar/syseng/gocode/src/github.com/opendns/lemming/lomax/lomax.go:298 +0x35
```

This isn't very informative and the user wouldn't really know what went wrong. We need to give better error messages.

**Comment by simar7** [comment]
https://github.com/opendns/lemming/commit/5c60815482ca1e994404274cf87dbd4db883a719 fixes this.
